window.sr = ScrollReveal();

    sr.reveal('.navbar',{
        duration:2000,
        origin:'bottom',
        distance:'-100px'
    });
    sr.reveal('.carousel',{
        duration:2000,
        origin:'bottom',
        distance:'-100px'
    });
    sr.reveal('.subtitulo',{
        duration:2000,
        origin:'top',
        distance:'400px'
    });
    sr.reveal('.carta--1',{
        duration:2000,
        origin:'left',
        distance:'400px'
    });
    sr.reveal('.carta--2',{
        duration:2000,
        origin:'right',
        distance:'400px'
    });
    sr.reveal('.seguros--1',{
        duration:2000,
        origin:'left',
        distance:'400px'
    });
    sr.reveal('.seguros--2',{
        duration:2000,
        origin:'right',
        distance:'400px'
    });
    sr.reveal('.seguros--3',{
        duration:2000,
        origin:'bottom',
        distance:'400px'
    });
    sr.reveal('.cajas--texto',{
        duration:2000,
        origin:'bottom',
        distance:'400px'
    });
    sr.reveal('.animacion--testimonio',{
        duration:2000,
        origin:'bottom',
        distance:'400px'
    });
    sr.reveal('.formulario',{
        duration:2000,
        origin:'left',
        distance:'400px'
    });
    sr.reveal('.carta--grande',{
        duration:2000,
        origin:'bottom',
        distance:'-100px'
    });